Exception: Failure "test".
Raised at Stdlib.failwith in file "stdlib.ml", line 35, characters 17-33
Called from <unknown> in file "pr9701.ml", line 5, characters 9-16
<<<<<<< HEAD
Called from Topeval.load_lambda in file "ocaml/toplevel/byte/topeval.ml", line 90, characters 4-14
||||||| 121bedcfd2
Called from Topeval.load_lambda in file "toplevel/byte/topeval.ml", line 89, characters 4-14
=======
Called from Topeval.load_lambda in file "toplevel/byte/topeval.ml", line 93, characters 4-14
>>>>>>> ocaml/trunk
